### ISSUE TITLE
Invalid check results

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#47] opened 2015-05-18 13:47 UTC
Unfortunately Prudge doesn't give a "Compilation Error" result. It just shows the message from compilator with an error but doesn't mark the the solution as wrong.

The other problem is that you can have a test where one integer is for an input and one for output. If you submit a solutions where the program is reading for two integers then Prudge won't give it "Idleness" result (because it didn't read one more variable) but will accept the solution. 

@ochko, can you fix such big problems please?

**Comment by ochko** [comment] 2015-05-24 12:02
Can you provide exact input, output and source code?

**Comment by alexbagirov** [comment] 2015-05-24 16:34
I have a simple A+B problem.
It has one test:
*Input: 2 3
*Output: 5
Source:
```
#include <iostream>
using namespace std;

int main() {
	kjkjjkj;
	return 0;
}
```
Afer submitting it will say that it has passed 0 tests and that's all. I think that it should mark it as a wrong solution.

**Comment by alexbagirov** [comment] 2015-05-24 16:41
Also there is a problem with a number of input integers (second part of the issue). We will submit a new solution for the same problem with same tests. Source:
```
#include <iostream>
using namespace std;

int main() {
	int a;
	cin >> a;
	cout << a;
	return 0;
}
```
It says that it has passed the first test (input 2 3 and output 5), but it says that it failed on the second which I have added. 
* Input - 23 45
*Output - 68
This solution tells 23 and it is marked as a wrong answer. So it has passed the first test but it shouldn't.

**Comment by ochko** [comment] 2015-05-29 14:50
> Afer submitting it will say that it has passed 0 tests and that's all.

That happens when your problem has no hidden test.

**Comment by ochko** [comment] 2015-05-30 06:11
The bug is fixed in https://github.com/ochko/prudge/commit/6c799732f0d79777a4f9bbdf2af8655b8cbff99c

**Comment by ochko** [comment] 2015-05-30 06:16
You reported another issue about compilation error. But I don't think that's a bug because compilation error could caused by mismatch between submitted code and particular compiler on your server. For example submitted code uses C++ 11 feature but compiler on the server doesn' support that feature. That case it is not user's fault, it is just user didn't know which compiler is running on the server. So user just need to update the solution and check again. In this case compiler error is helpful for user to know why his code didn't compile.

**Closed by ochko** 2015-05-30 06:16 UTC
Labels: bug
